services:
  - type: web
    name: plant-disease-detection 
    env: python
    runtime: python-3.11 
    buildCommand: pip install torch==2.8.0 torchvision==0.23.0 --index-url https://download.pytorch.org/whl/cpu && pip install -r requirements.txt
    startCommand: python3 app.py