services:
  - type: web
    name: plant-disease-detection
    env: python
    runtime: python-3.11
    region: us-east
    plan: free 
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000